[package]
name = "tetris"
version = "0.1.0"
edition = "2021"


[dependencies]
rodio = { version = "0.15", default-features = false, features = [
  "symphonia-wav",
  "symphonia-mp3",
] }
termios = "0.3"
spin_sleep = "1.1"
nix = { version = "0.24", default-features = false, features = ["signal"] }
libc = "0.2"
rand = "0.8"
once_cell = "1.12"
anyhow = "1"
lazy_static = "1.4"
kdl = "4.3"
