[package]
name = "tetris"
version = "0.1.0"
edition = "2021"


[dependencies]
rodio = { version = "0.15", default-features = false, features = [
  "symphonia-wav",
  "symphonia-mp3",
] }
kdl = "4.6"
termios = "0.3"
libc = "0.2"
rand = "0.8"
byteorder = "1.4"
once_cell = "1.17"
anyhow = "1"
