[package]
name = "tetris"
version = "0.1.0"
edition = "2024"


[dependencies]
rodio = "0.20"
kdl = "6"
termios = "0.3"
ftail = "0.3"
log = "0.4"
libc = "0.2"
rand = "0.9"
once_cell = "1"
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
log-panics = "2.1"
clap = { version = "4.5.40", features = ["derive"] }
