[workspace]
members = ["cli", "web"]
default-members = ["cli"]

[workspace.dependencies]
anyhow = "1"
log = "0.4"
rand = "0.9"

[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
kdl = "6"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
log.workspace = true
anyhow.workspace = true
rand.workspace = true
