[package]
name = "tetris"
version = "0.1.0"
edition = "2021"


[dependencies]
rodio = { version = "0.19", default-features = false, features = [
  "symphonia-wav",
  "symphonia-mp3",
] }
kdl = "4"
termios = "0.3"
ftail = "0.3"
log = "0.4"
libc = "0.2"
rand = "0.8"
once_cell = "1"
anyhow = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
